export const ENV_VARS = {
    PORT: 'PORT',

    MONGODB_USER: 'MONGODB_USER',
    MONGODB_PASSWORD: 'MONGODB_PASSWORD',
    MONGODB_URL: 'MONGODB_URL',
    MONGODB_DB: 'MONGODB_DB',

    SMTP_PORT: 'SMTP_PORT',
    SMTP_HOST: 'SMTP_HOST',
    SMTP_USER: 'SMTP_USER',
    SMTP_PASSWORD: 'SMTP_PASSWORD',
    SMTP_FROM: 'SMTP_FROM',

    FRONTEND_DOMAIN: 'FRONTEND_DOMAIN',
    BACKEND_DOMAIN: 'BACKEND_DOMAIN',
    JWT_SECRET: 'JWT_SECRET',

    CLOUDINARY_API_KEY: 'CLOUDINARY_API_KEY',
    CLOUDINARY_API_SECRET: 'CLOUDINARY_API_SECRET',
    CLOUDINARY_API_CLOUD_NAME: 'CLOUDINARY_API_CLOUD_NAME',
    FILE_STORAGE_STRATEGY: 'FILE_STORAGE_STRATEGY'
};